version: '3'
services:
  rewardCentral:
    image: tourguide/tourguiderewardcentral
    ports:
      - "8083:8080"
    restart: always
  tripPricer:
    image: tourguide/tourguidetrippricer
    ports:
      - "8082:8080"
    restart: always
  gpsUtil:
    image: tourguide/tourguidegpsutils
    ports:
      - "8081:8080"
    restart: always
volumes:
  db_data: {}