version: '3'
services:
  rewardCentral:
    image: tourguide/tourguiderewardcentral
    ports:
      - "8083:8080"
    restart: always
  tripPricer:
    image: tourguide/tourguidetrippricer
    ports:
      - "8082:8080"
    restart: always
  gpsUtil:
    image: tourguide/tourguidegpsutils
    ports:
      - "8081:8080"
    restart: always
  tourGuide:
    depends_on:
      - gpsUtil
      - tripPricer
      - rewardCentral
    image: tourguide/tourguide
    ports:
      - "8080:8080"
    restart: always
    environment:
      gpsutil: gpsUtil:8081
      trippricer: tripPricer:8082
      rewardcentral: rewardCentral:8083

volumes:
  db_data: {}