/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TourGuildeGpsUtils;

import org.junit.Test;
import static org.junit.Assert.*;

public class GpsUtilController {
    @Test public void testSomeLibraryMethod() {
        GpsUtilController controller = new GpsUtilController();
        
    }
}
